### ISSUE TITLE
Feature: TS declaration file 

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/inspectpack#76]
- [ ] Decide on what the public API should _actually_ be.
- [ ] See if we can auto-generate the `.d.ts` file.

**Comment by jensbodal** [comment]
Is there any reason that you're not just setting `declaration: true` in the tsconfig? I was converting our webpack config to typescript and had to use `declare module inspectpack` for this library since it doesn't ship types.  Seems odd to not do it since it's already been rewritten in typescript.  Here's a PR if you want it: https://github.com/FormidableLabs/inspectpack/pull/160
